modLoader="javafml"
loaderVersion="[28,)"

[[mods]]
modId="houndmod"
version="1.4.3"
displayName="HoundMod"
credits="Ce mod a été créé par Helie__ sur le logiciel Mcreator."
displayURL="https://curseforge.com/minecraft/mc-mods/houndmod"
logoFile="logo.png"
authors="Helie__"
description='''
Ce mod rajoute différentes armures et items.
'''

[[dependencies.houndmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"



